export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const STAFF_DETAILS_REPOSITORY = 'STAFF_DETAILS_REPOSITORY';
export const jwtConstants = 'secret';
export const VEHICLE_REPOSITORY = 'VEHICLE_REPOSITORY';
export const QUOTES_REPOSITORY = 'QUOTES_REPOSITORY';
export const RENTALS_REPOSITORY = 'RENTALS_REPOSITORY';
